services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - STORE_MODEL_IN_DB=${STORE_MODEL_IN_DB}
      - PORT=${PORT}
      - TZ=America/Los_Angeles
    command: --config /app/config.yaml --detailed_debug
    restart: unless-stopped