
router_settings:
  database_url: ${DATABASE_URL}
  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  aws_region: ${AWS_REGION}
  master_key: ${LITELLM_MASTER_KEY}
  litellm_salt_key: ${LITELLM_SALT_KEY}
  store_model_in_db: ${STORE_MODEL_IN_DB}
  port: ${PORT}